name: "Install Dependencies"
description: "Action to build the project dependencies from the main versions"
inputs:
  python_version:
    required: true
    type: string
    default: "3.11.6"

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - name: Install uv and set the python version
      uses: astral-sh/setup-uv@v5
      with:
        python-version: 3.11.6
    - name: Install the project
      run: uv sync --all-extras --dev
      shell: bash
